<div class="container">
    <div class="row">
        <h2>Actualizar Cuenta </h2>
        <div class="row">
            <form class="col s12 " action="<?php echo APP_URL?>account/edit/<?= $this->get('account')['id'] ?>" method="post">
                <div class="row">
                    <div class="input-field col s12">
                        <input class="validate" id="name" name="name" type="text" value="<?= $this->get('account')['name'] ?>" required/>
                        <label for="name">Nombre</label>
                    </div>
                </div>


                <div class="row">
                    <div class="input-field col s12">
                        <button class="btn waves-effect waves-light" type="submit" name="action">Guardar
                            <i class="material-icons right">send</i>
                        </button>
                    </div>
                </div>
            </form>

        </div>
    </div>
</div>