<div class="container">
    <div class="row">
        <h2>Actualiza la transacción</h2>
        <div class="row">
            <form class="col s12 " action="<?php echo APP_URL?>transaction/edit/<?= $this->e($this->get('transaction')['id']) ?>" method="post">
                <div class="row">
                    <div class="input-field col s12">
                        <select name="account_id" >
                            <option disabled selected>Elegir Una Cuenta</option>
                            <?php foreach ($this->get('accounts') as $account):?>
                                <option value="<?= $account['id'] ?>" <?= $account['id'] === $this->get('transaction')['account_id'] ? ' selected' : ''?>><?= $account['name'] ?></option>
                            <?php  endforeach?>
                        </select>
                        <label >Cuenta</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12">
                        <select name="category_id" >
                            <option disabled selected>Elegir Una categoría</option>
                            <?php foreach ($this->get('categories') as $category):?>
                                <option value="<?= $category['id'] ?>" <?= $category['id'] === $this->get('transaction')['category_id'] ? ' selected' : ''?>><?= $category['name'] ?></option>
                            <?php  endforeach?>
                        </select>
                        <label >Categoría</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12">
                        <input class="validate" id="description" name="description" type="text" value="<?= $this->e($this->get('transaction')['description']) ?>" required/>
                        <label for="description">Descripción</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12">
                        <input step="any" class="validate" id="amount" name="amount" type="number" value="<?= $this->e($this->get('transaction')['amount']) ?>" required/>
                        <label for="amount">Monto</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12">
                        <label>Fecha</label>
                        <input class="datepicker"  type="text" name="date" value="<?=$this->get('transaction')['date'] ?>"/>
                    </div>
                </div>



                <div class="row">
                    <div class="input-field col s12">
                        <button class="btn waves-effect waves-light" type="submit" name="action">Guardar
                            <i class="material-icons right">send</i>
                        </button>
                    </div>
                </div>
            </form>

        </div>
    </div>
</div>